### ISSUE TITLE
Build Failed Issue please check it and inform 

### ISSUE THREAD

**Issue by punisher-303** [HemantKArya/BloomeeTunes#11]
can you check it and replay ?

![image](https://github.com/user-attachments/assets/24761445-e23c-4894-ba99-4718fd1c4053)

**Comment by HemantKArya** [comment]
I think the problem is keystore files and secretes. cause you building without it. I may remove these from building apk builds in future.

**Comment by punisher-303** [comment]
I just take your repository and using it in GitHub action your build is
successes and why my actions is fails that's what I got this doubt

**Comment by punisher-303** [comment]
> I think the problem is keystore files and secretes. cause you building without it. I may remove these from building apk builds in future.

Can you mention that secretes environment of GitHub action

**Comment by HemantKArya** [comment]
Don't worry I will remove it and build app using GitHub action without app obfuscation.
