### ISSUE TITLE
How to access lyrics

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [HemantKArya/BloomeeTunes#17]
Unable to access lyrics for songs means dont know how to

**Comment by HemantKArya** [comment]
Hi @ALMIGHTY-VC  thanx for reaching out to issue section🤗. The lyrics feature is still intact in bloomee and I going to implement a robust feature for that in future. So, for now, for there is no lyrics option but i will make sure to implement it soon. And if anyone want to contribute this project welcome all the ideas for that.

**Comment by ALMIGHTY-VC** [comment]
> Hi @ALMIGHTY-VC thanx for reaching out to issue section🤗. The lyrics feature is still intact in bloomee and I going to implement a robust feature for that in future. So, for now, for there is no lyrics option but i will make sure to implement it soon. And if anyone want to contribute this project welcome all the ideas for that.

Oh thanks bhai i can suggest some lyrics provider to you like lrclib kugou and
In that case, you can consider the following lyrics providers that offer license-free or open-source options:

1. _Lyrics.ovh_: A simple, open-source lyrics API with a decent database.
2. _LyricWiki_: A wiki-based lyrics database with a vast collection and API access, licensed under Creative Commons.
3. _Wikia's LyricWiki API_: Similar to LyricWiki, but with a more extensive database.

Keep in mind that while these options don't require licenses, they might have usage guidelines or restrictions. Be sure to review their terms and conditions to ensure you comply with their requirements.

Additionally, you can also consider:

1. _OpenLyrics_: An open-source lyrics database with a small but growing collection.
2. _LyricsFreak_: A lyrics database with a large collection, but be aware that their API terms are not clearly defined.

Remember to always verify the terms and conditions of any provider before integrating their API into your application.
Credits- Meta Ai 
Dhanyawaad bhai

**Comment by ALMIGHTY-VC** [comment]
https://github.com/surfbryce/beautiful-lyrics
Or you can implement this too it will ease your work as well

**Comment by HemantKArya** [comment]
thanx @ALMIGHTY-VC I am looking into it. It will help a lot 😊.

**Comment by HemantKArya** [comment]
Hi @ALMIGHTY-VC  Lyrics features is now implemented 🎉 in 49761b0f523b54c3c4a675deeb53dfa9bf106e61 . You can now use either by swiping the cover art or small button at the bottom of the player screen. 🤗
Now I think this issue needs to be closed.

**Comment by ALMIGHTY-VC** [comment]
> Hi @ALMIGHTY-VC Lyrics features is now implemented 🎉 in [49761b0](https://github.com/HemantKArya/BloomeeTunes/commit/49761b0f523b54c3c4a675deeb53dfa9bf106e61) . You can now use either by swiping the cover art or small button at the bottom of the player screen. 🤗 Now I think this issue needs to be closed.

Very noice thanks bro
