### ISSUE TITLE
YouTube music playlist import 

### ISSUE THREAD

**Issue by aneesh1122** [HemantKArya/BloomeeTunes#19]
Right now the app can only import from YouTube. please add the option to import from YouTube music too.

I know that I can simply import the same playlist from YouTube but the album cover is not in 1:1 ratio.

**Comment by HemantKArya** [comment]
Thanx for noticing @aneesh1122 I will look surely work on this too.

**Comment by aneesh1122** [comment]
> Thanx for noticing @aneesh1122 I will look surely work on this too.

Thanks bhai

**Comment by HemantKArya** [comment]
Hi @aneesh1122 , this feature is now implemented in this 69ed6e339b1bc2fb1ebf000a0e33500bea9f3892 commit. 🤗 Now I think this issue needs to be closed.

**Comment by aneesh1122** [comment]
> Hi @aneesh1122 , this feature is now implemented in this 69ed6e339b1bc2fb1ebf000a0e33500bea9f3892 commit. 🤗 Now I think this issue needs to be closed.

Thanks bhai. Sure, close this issue :)
