### ISSUE TITLE
Hey bro

### ISSUE THREAD

**Issue by Fxrrcrxdsccexxe** [HemantKArya/BloomeeTunes#2]
Hi will u make Android TV compatible.. @HemantKArya

**Comment by HemantKArya** [comment]
Yes @Fxrrcrxdsccexxe 😊 I'm planning to make it compatible in future releases.

**Comment by Fxrrcrxdsccexxe** [comment]
Thank u 🙏@HemantKArya

**Comment by Fxrrcrxdsccexxe** [comment]
Hey bro plz add queue option in player

**Comment by HemantKArya** [comment]
Sure, I will.
