### ISSUE TITLE
Remove 'DEPENDENCY_INFO_BLOCK' from compiled apk and  'android:usesCleartextTraffic="true"' line from manifest file.

### ISSUE THREAD

**Issue by tronizx** [HemantKArya/BloomeeTunes#21]
Since 'DEPENDENCY_INFO_BLOCK' can only be read by Google there is no need to include in this app and also 'ClearTextTraffic =true' is also problematic for security reasons if any feature is using this attribute, then we should mention it or remove this from this app.

**Comment by HemantKArya** [comment]
Resolved in commit d6c99ee2ebb527f3a2c7f4d8d903bd1601582510
