### ISSUE TITLE
Detections in virus total

### ISSUE THREAD

**Issue by Runixe786** [HemantKArya/BloomeeTunes#24]
So I posted your app on my telegram channel and a subscriber there find some detections in the app upon checking from virus total. I believe they are false positives so do fix them as soon as possible. Thanks ![image](https://github.com/user-attachments/assets/ff1e7f25-49e0-4683-99a5-32d3fbb02b11)

**Comment by HemantKArya** [comment]
Yeah thanx @Runixe786, I am well aware of this false positive, so I am looking into it and make sure to remove this. about this Avast one I found a link that this is false positive here is the ref:  https://forum.avast.com/index.php?topic=320537.0

**Comment by HemantKArya** [comment]
I don't think now this issue still persist, so right now I am closing this issue feel free to reopen if it appears again.
Thanx for mentioning this btw 🤗
