### ISSUE TITLE
Plz add queue feature

### ISSUE THREAD

**Issue by Fxrrcrxdsccexxe** [HemantKArya/BloomeeTunes#3]
Hey bro plz add queue option in player @HemantKArya

**Comment by HemantKArya** [comment]
Yeah I will impl. it in future versions. but I already answered you in different issue opened by you.

**Comment by HemantKArya** [comment]
> Hey bro plz add queue option in player @HemantKArya

Hi @Fxrrcrxdsccexxe queue is now implemented in 3a83bf8b20e46f9fd285a512bca1feee12682b61
