### ISSUE TITLE
Add Lyrics Provider with search option.

### ISSUE THREAD

**Issue by adilurrhmn** [HemantKArya/BloomeeTunes#34]
Add this
https://lrclib.net/

Along with search option that we can search lyrics manually

**Comment by HemantKArya** [comment]
Hi @adilurrhmn  thanx for you advice this app is already utilizing `LRCLib` for lyrics related work and yeah, I already have in mind to implement this feature after I will be done with current work.
Again, Thanx for opening this issue it will be tracked in future to implement a search feature for custom lyrics.

**Comment by adilurrhmn** [comment]
Turn off these slide sources , bit still showing empty spaces.
![Screenshot_2024-08-28-21-04-51-18_dafff40a4121cf68ccb459f939d7eea0](https://github.com/user-attachments/assets/07abdc45-85d4-4ece-a9c7-66b7e27ef73c)

**Comment by adilurrhmn** [comment]
![Screenshot_2024-08-29-11-41-15-91_dafff40a4121cf68ccb459f939d7eea0](https://github.com/user-attachments/assets/2b36662a-efd0-4abe-b208-ea4dd6221719)

**Comment by HemantKArya** [comment]
Okay @adilurrhmn, it seems this bug is only showing in some devices, I will definitely look into this bug. And let me know if something happens anything else related to charts here in this issue.

**Comment by adilurrhmn** [comment]
If I find any bugs, then I will update it here.

**Comment by HemantKArya** [comment]
Thanx you @adilurrhmn 🥰, you can also open separate issue for different issue so that they can be tracked individually from there. 
About this bug -> 

> Turn off these chart sources, but still showing empty spaces.
 It will be solved in next build.

**Comment by HemantKArya** [comment]
Hi @adilurrhmn I hope this charts bug is now solved can you verify here if it is.

**Comment by adilurrhmn** [comment]
Yes. Solved

**Comment by HemantKArya** [comment]
This feature is now implemented.
You can see a setting icon in right bottom of lyrics widget from where you can search lyrics manually and select them.
Thanx for suggesting this idea @adilurrhmn 😊
