### ISSUE TITLE
Ability to like albums

### ISSUE THREAD

**Issue by LokNplay** [HemantKArya/BloomeeTunes#39]
For now, we can only like music. It will be nice of we can do the same for albums.

**Comment by HemantKArya** [comment]
yeah sure @LokNplay this feature to search album/playlist/artist is recently released and I will make sure to update this in our future releases so that we can add them in our library and also sync them with local DB.

**Comment by HemantKArya** [comment]
Hi @LokNplay this feature is now implemented in 443686aa1f3a17e744855a43726b06bf6c093f6a commit. If it fine, then I think this issue needs to be closed.
