### ISSUE TITLE
Playlist sequence modification

### ISSUE THREAD

**Issue by dewxo** [HemantKArya/BloomeeTunes#41]
I would like to map playlists songs in a sequence  which would give more vibe shifting(idk if it's implemented I couldn't find it)

+Feature +Enhancement

**Comment by HemantKArya** [comment]
Hi @dewxo , thanx for reaching out, are you refereeing to reorder the playlist's items so that it can played in your own favorite order?

**Comment by dewxo** [comment]
Yes

**Comment by HemantKArya** [comment]
I think it is already there you can do it by->
1. clicking at 3 dots next to play button inside playlist
2. then you see edit playlist option
3. a new screen will appear you can reorder by selecting them using long press
4. save playlist by clicking check button at top right.

**Comment by dewxo** [comment]
Ohh got it, thanks!

I'm leaving a Screenshot that it may help someone in future.

![Screenshot_2024-09-03-19-28-34-966_ls.bloomee.musicplayer-edit.jpg](https://github.com/user-attachments/assets/6f2bb590-2307-418b-8d1a-c258b3f16bbb)

**Comment by HemantKArya** [comment]
You're welcome @dewxo 🤗.
