### ISSUE TITLE
YouTube Music Login Support for Personalization and Sync

### ISSUE THREAD

**Issue by Rafee-M** [HemantKArya/BloomeeTunes#43]
I believe it would make it more easier if users could login and have their music personalization be synced to YTM if they wished to do so.

This could also sync playlists and other data as well with YTM and make it more convenient.

Apps that do this: InnerTune, SimpMusic, SpMp

**Comment by HemantKArya** [comment]
Thanx for suggesting this idea @Rafee-M I will make sure to check this idea out and if anyone want to submit any PR related to this, I will welcome them open heartly.
Since it seems like it is duplicate then we will discuss more about this in https://github.com/HemantKArya/BloomeeTunes/issues/35.

**Comment by Rafee-M** [comment]
Thanks a lot for the response! I'll close the issue then
