### ISSUE TITLE
Latest update no longer runs in background or uses media player

### ISSUE THREAD

**Issue by GrandVizierNappa** [HemantKArya/BloomeeTunes#44]
After updating the background process doesn't stay as well as the media player on the notification and lock screen doesn't activate. Older version 2.9.5 works 2.9.9 doesn't

**Comment by HemantKArya** [comment]
Hi @GrandVizierNappa thanx for reporting this. I am currently looking into it and tried it in android 14 emulator and the notification is not working while in another devices and older ones too it is working fine. However, as you are saying the older version of app is working fine then I have to look closely what's is changed that caused it. And if anyone find any workaround or solution, please let me know here or submit a PR.

**Comment by HemantKArya** [comment]
Also but in my case it is running fine in background. 😐

**Comment by GrandVizierNappa** [comment]
I have tried it on 2.9.6 which I thought would work and it doesn't only the 2.9.5 seems to be the one that works I thought I was losing my mind as I tried every setting permission and other tweaks to get it to work

**Comment by HemantKArya** [comment]
so are you saying that 2.9.5 is working fine ?

**Comment by GrandVizierNappa** [comment]
Yes the latest 2.9.5

**Comment by HemantKArya** [comment]
Hi, @GrandVizierNappa can you verify if the problem still exists in latest release `v2.9.10`?

**Comment by GrandVizierNappa** [comment]
Downloaded the 2.9.11 update so far it seems to be running going to give it a few days to see if a cache clear doesn't change anything

**Comment by HemantKArya** [comment]
how about media notification?

**Comment by GrandVizierNappa** [comment]
@HemantKArya giving it a bit of time as for media controls it now works on the lockscreen as well as the notification center. As for getting notifications about certain things from the app notifications was turned off and i am unable to verify however getting an in-app notifications still inform me when there is an update. as for your question i am confused on what you mean exactly on this.

**Comment by HemantKArya** [comment]
Okay then after you feel that the main objective of this issue is fixed then please male sure to close this issue. 
And thanks for always helping me by notifying these issues. 😊
