### ISSUE TITLE
Shows No Internet on Bluetooth Tethering

### ISSUE THREAD

**Issue by Priyanshu-apk** [HemantKArya/BloomeeTunes#49]
It shows No Internet on Bluetooth Tethering but works fine in Wifi Network. Also app animations and transitions are beautiful but please try to make app theme more minimalistic and material themed
❤️🇮🇳

**Comment by HemantKArya** [comment]
Okay I will look into that Thanx for reporting this issue @Priyanshu-apk 🥰

**Comment by HemantKArya** [comment]
Hi @Priyanshu-apk this issue is not fixed in latest release can you verify here if it is now resolved.
https://github.com/HemantKArya/BloomeeTunes/releases/tag/v2.10.1%2B144

**Comment by Priyanshu-apk** [comment]
I tried installing the app but after opening it shows just a grey and black page 

![Screenshot_20241004-234828](https://github.com/user-attachments/assets/04393e54-0a7f-4e84-9984-c9a56fce099f)

**Comment by HemantKArya** [comment]
was the previous one was working fine?

**Comment by Priyanshu-apk** [comment]
Yes

**Comment by HemantKArya** [comment]
okay I am looking into that. it is really unstable I guess.

**Comment by HemantKArya** [comment]
https://github.com/HemantKArya/BloomeeTunes/releases/tag/v2.10.4%2B147
can you check this?

**Comment by Priyanshu-apk** [comment]
Hi this time app is opening as normal and also seek option in notification panel is now visible and I can control playback perfectly but Bluetooth Tethering problem is still there. 
Earlier it was showing No Internet but now it shows this error.

**Comment by Priyanshu-apk** [comment]
![Screenshot_20241005-102514](https://github.com/user-attachments/assets/80f95c2c-6246-4c15-912e-7645ff575455)
![Screenshot_20241005-102440](https://github.com/user-attachments/assets/feebb3e0-8e04-4a33-8bf7-1f446c966360)

**Comment by HemantKArya** [comment]
I guess there is no error from this side cause in previous version I intentionally added to de-recognise the Bluetooth internet but now I just removed that condition so it must work if it is working in other apps.

**Comment by Priyanshu-apk** [comment]
Bluetooth Tethering is working fine in other apps as I used Bluetooth Tethering to download the latest version of bloome from github.

**Comment by Priyanshu-apk** [comment]
Oh sorry I think you are right. There's some issue from my side. I need some time to fix this

**Comment by HemantKArya** [comment]
okay @Priyanshu-apk I think now this issue need to be closed then.

**Comment by Priyanshu-apk** [comment]
Ok
