### ISSUE TITLE
Can't control playback in quick settings 

### ISSUE THREAD

**Issue by Priyanshu-apk** [HemantKArya/BloomeeTunes#50]
I am using Android 14 on Motorola ....I found one more bug. I can't use the slider to chose timestamp of music means I can't listen  favourite line of the song again without opening the app, it just keeps playing continuously. 

Please have a look at screenshot 
![Screenshot_20240928-162207](https://github.com/user-attachments/assets/902d2e4e-2f8d-44a8-9ac6-f38c1503b7f7)

And thank you for this app ❤️

**Comment by Priyanshu-apk** [comment]
![Screenshot_20240928-162207~2](https://github.com/user-attachments/assets/530885de-6ae5-4d0a-acea-725e7d2c874c)

**Comment by HemantKArya** [comment]
Yeah, I will make sure to look into this.

**Comment by soulspark666** [comment]
```1727587081.361  1000  1469  3963 E NotificationVibratorHelper: Error creating vibration waveform with pattern: [0]```

Hi, I found this in adb logcat, hope it helps.

**Comment by HemantKArya** [comment]
Thanx @Priyanshu-apk for this help. actually, I just fixed it in the latest commit d9a06f28e1f2c8a707da7f48375d0d28733936ab , so just wait for next release let me know if it works.

**Comment by HemantKArya** [comment]
Hi @soulspark666 and @soulspark666 this is issue is now fixed in new update, if you can verify it here will be helpful.
https://github.com/HemantKArya/BloomeeTunes/releases/tag/v2.10.1%2B144

**Comment by Priyanshu-apk** [comment]
This issue is resolved in the latest version. Thank you

**Comment by HemantKArya** [comment]
welcome, and thanx for submitting these issues. 😊
