### ISSUE TITLE
App not functional

### ISSUE THREAD

**Issue by n3rdcub** [HemantKArya/BloomeeTunes#54]
Pixel 7 a15 beta, app looks nice and has potential, but nothing works on it. Can't play songs, can't download, can't search, can't do anything.

**Comment by HemantKArya** [comment]
Can you mention some screenshots and also os and version so that I can try to debug on that particular version, cause in my case it is working fine not only mine but in lot of other devices.

**Comment by dotcs** [comment]
Same for me on an Pixel 6a, Android 14 Build `AP2A.240905.003.F1`.
Loading spinner keeps circling when trying to play a song. Besides audio the app is working fine. Covers and playlists are loaded.

**Comment by HemantKArya** [comment]
Okay then I guess it must be something related to android 14 or Pixel device, I will look into that matter let you all know about if something comes out.

**Comment by juanjgit** [comment]
Same in Android 11

**Comment by HemantKArya** [comment]
I am glad @juanjgit you noticed it since the newer version already resolve this issue.

**Comment by HemantKArya** [comment]
Just tested Bloomee in Pixel 6a Android 14 and it ran without any issue.
![Screenshot_1729236646](https://github.com/user-attachments/assets/bfb28a20-25bf-46dd-a0c2-3e664ef66ab4)

If anyone have other issue related to this or can give me some more insights possible then please discuss here.

**Comment by ansarimohammed422** [comment]
Same here 
Poco x4 pro hyper os 
Android 13

The songs are just loading endelessly

**Comment by HemantKArya** [comment]
Hi, @ansarimohammed422 this issue seems different, so it needs to resolve in different issue thread. Please if possible can you open new issue for this problem cause this one to seem already resolved.
