### ISSUE TITLE
Nothing works in the app no search result, no playback

### ISSUE THREAD

**Issue by gr8abhi** [HemantKArya/BloomeeTunes#66]

**Comment by HemantKArya** [comment]
Can you add more details like device name, OS name, OS version or anything that can help me to track this issue? 
btw thanx for submitting this issue.

**Comment by gr8abhi** [comment]
Android 12
Motorola G40

**Comment by gr8abhi** [comment]
Android 12
Motorola G40

**Comment by gr8abhi** [comment]
I did a fresh install from apk downloaded from source forge app is working now. Earlier i downloaded app from droid-ify.

**Comment by HemantKArya** [comment]
Ahh..... I see right now we have some problem there and latest version of app is not available except Github and Sourceforge (From Mine side).
