### ISSUE TITLE
Doesn't show lyrics for any song

### ISSUE THREAD

**Issue by imbackwithrampage** [HemantKArya/BloomeeTunes#67]
Please fix lyrics for songs and currently it is showing there is no lyrics

**Comment by HemantKArya** [comment]
Hi @imbackwithrampage can you check some more songs cause right now I can see lyrics in my all platforms and devices. Or you can mention some more details that can lead me to the same error and then I can try to resolve that.

**Comment by imbackwithrampage** [comment]
Hi @HemantKArya actually i checked 2 to 3 tamil latest songs like "dheema dheema" and "hey minnale", it says the provider is from jiosaavn but in jiosaavn it has lyrics, not in our bloometunes platform. It shows there is no lyrics.
![Screenshot (49)](https://github.com/user-attachments/assets/7cfe0a35-5b37-4827-b3ed-efa15a5d5ab7)
![Screenshot (50)](https://github.com/user-attachments/assets/c7eae888-f5b5-40b7-acd2-98e064ca22d2)

**Comment by HemantKArya** [comment]
Thank you @imbackwithrampage for clearing out I just tried out those songs and found out that these same songs are working fine with `YTM search` but not in `JISaavn` one. I guess it is problem related to lyrics search using metadata. I will definitely be looking into it.

**Comment by imbackwithrampage** [comment]
Thankyou so much @HemantKArya. You've done a great job. I'm so happy and satisfied to use this application. I hope and damn sure u'll fix this bug soon enough possible.

**Comment by HemantKArya** [comment]
Hi, @imbackwithrampage this issue is resolved in latest version. and if in some song's lyrics doesn't work now you have a small setting icon in lyrics widget from where you can search and select the lyrics manually.
For now, I think this issue needs to be closed.
Thanx for reporting the issue. 😊

**Comment by imbackwithrampage** [comment]
@HemantKArya Thank you so much brother. Looking forward for your future updates.
