### ISSUE TITLE
Unable to load JioSaavan playlists

### ISSUE THREAD

**Issue by StarOne01** [HemantKArya/BloomeeTunes#69]
The issues **doesn't** appear on the **first time** after i clear all the app data.

![Screenshot_2024-10-31-12-41-22-54_dafff40a4121cf68ccb459f939d7eea0.jpg](https://github.com/user-attachments/assets/d7b92eaf-03ee-4970-add3-a58748196964)

but once i close the app and re open it, the issue appears

![Screenshot_2024-10-31-12-37-38-30_dafff40a4121cf68ccb459f939d7eea0.jpg](https://github.com/user-attachments/assets/be089c3e-b118-4eb1-8dca-4447406064fe)

It just bufferss.. and bufferss.. endlessly

**Comment by StarOne01** [comment]
I just found out that, this issues appears after i give the app storage permission (which appears the first time i try to download a song).

If i deny it, close the app and re-open it. The issues doesn't appear.

**Comment by HemantKArya** [comment]
As far as I know storage permission is not related to online album view. Also, I am not able to replicate this issue so if it is possible for you then can you please mention some more details related to your platform where you are using this app, OS, OS Ver or anything else like device etc.

**Comment by StarOne01** [comment]
I'm sorry, that has nothing to do with storage permission. Rather, i'm unable to access JioSaavan playlists from library.

Version: 2.10.8
OS: Android 14 + Realme UI 4.0

**Comment by HemantKArya** [comment]
Thank you @StarOne01 for helping me out 😊. This issue is now resolved in commit 350b91d1b05a01350ffbcdf23939ebd6a0c2e47a. And probably will be released with new builds in future.

**Comment by StarOne01** [comment]
Thank you so much for the fix and here is a complement, the app is just wonderful. Thanks for this.

**Comment by HemantKArya** [comment]
Thanx again for your complement @StarOne01 🤗
