### ISSUE TITLE
change download directory to music 

### ISSUE THREAD

**Issue by rajarshikhatua100** [HemantKArya/BloomeeTunes#71]
change the default download directory from "/storage/emulated/0/Android/data/ Is.bloomee.musicplayer/files/downloads" to "/storage/emulated/0/Music"

**Comment by ConEstArthur** [comment]
Need the same.

**Comment by HemantKArya** [comment]
Hi @ConEstArthur and @rajarshikhatua100 , you can change the download directory from settings of this app.

**Comment by ConEstArthur** [comment]
> Hi @ConEstArthur and @rajarshikhatua100 , you can change the download directory from settings of this app.

Thanks, it's working now.
Btw has Jiosaavn stopped working? When I search something it renders no results.

**Comment by HemantKArya** [comment]
Ur Welcome 😊.

> Btw has Jiosaavn stopped working? When I search something, it renders no results.

Working fine from in my device.
I think i need to close this issue for now since it is already available in settings.

**Comment by ConEstArthur** [comment]
@HemantKArya I'm able to change the directory to music but it's not able to download to it.
It can only download to its default location.

I think the problem would be solved if it asks me to access all my files (as mixplorer asks or obsidian does) instead it asks Photos and Videos access.

**Comment by HemantKArya** [comment]
did you tried with explicitly providing all permission to it?

**Comment by ConEstArthur** [comment]
> did you tried with explicitly providing all permission to it?

Yes I have.
Sadly it still fails.
Also even when I download from Jiosaavn, it downloads in mp4 format and size is rather low.

**Comment by HemantKArya** [comment]
Okay the directory problem does exist for sure I know, but the second one size of music is problem that we need to still figure out to download high quality audio from different server since jiosaavn or music both provide streaming format not high quality mp3 or other formats.

**Comment by RealFakeGitter** [comment]
> Hi [@ConEstArthur](https://github.com/ConEstArthur) and @rajarshikhatua100 , you can change the download directory from settings of this app.

How do I change the location? In download settings I see the location but clicking it doesn't do anything the whole field seems disabled
