### ISSUE TITLE
[Other] How can I buy you a cup of coffee?

### ISSUE THREAD

**Issue by StaringLongingly** [HemantKArya/BloomeeTunes#8]
I just love this project and want to see it grow :)

**Comment by HemantKArya** [comment]
Thanx you so much 🥰 @StaringLongingly, your suggestions are helping me so much I will soon make available these options.

**Comment by HemantKArya** [comment]
Hi @StaringLongingly , Thanx for suggesting me this in past. Now I guess is right time to setup an account and here it is. 

<a href="https://liberapay.com/hemantkarya/donate"><img alt="Donate using Liberapay" src="https://liberapay.com/assets/widgets/donate.svg"></a>
