### ISSUE TITLE
[Bug] Spotify playlist import doesn't import the playlist icon and uses the artwork of the first song

### ISSUE THREAD

**Issue by StaringLongingly** [HemantKArya/BloomeeTunes#9]
self-explanatory

**Comment by HemantKArya** [comment]
yeah, you are right, and I know many platforms are using this kind of setup like showing playlist cover art different than songs it contains. But currently I thought to show playlist cover as only the songs it contains and in future version, I hope it show cover of playlist by showing the preview of songs it contains.

**Comment by HemantKArya** [comment]
hi @StaringLongingly thanx to your recommendation now this import feature is updated in commit be60ad7ad519d6793ec99ab282cb2c97fc7335e9, so now if you import any playlist then its thumbnail by default is artwork of original playlist's cover art from where you imported it.
Now I think this issue need to be closed if you find this helpful.

**Comment by StaringLongingly** [comment]
Thank you
