### ISSUE TITLE
jiosaavn search does not work

### ISSUE THREAD

**Issue by ConEstArthur** [HemantKArya/BloomeeTunes#90]
Search through jiosaavn provider is sadly not working for me.
I'm on A14 Lineage os.
![Screenshot_20241224-013816_Bloomee](https://github.com/user-attachments/assets/95badd7b-0855-4050-84ae-50e64726fa9f)

**Comment by HemantKArya** [comment]
Hi @ConEstArthur , can you inform me again if it is working for your device or not?

**Comment by ConEstArthur** [comment]
> Hi @ConEstArthur , can you inform me again if it is working for your device or not?

Working in the latest build.
Thanks a lot :)

**Comment by HemantKArya** [comment]
Ur welcome 😊.
