### ISSUE TITLE
v2.10.10.+154] App Not Loading Music too on Windows 11 (x64)

### ISSUE THREAD

**Issue by Devsathome** [HemantKArya/BloomeeTunes#94]
Description:
The app version v2.10.10.+154 (x64) does not load music on Windows 11.show offline  The previous version, v2.10.9+154 (x64), works perfectly under the same conditions. 

Steps to Reproduce:

Install v2.10.10.+154 (x64) on Windows 11.
Attempt to load music.
Observe that the app fails to load music.

Observed Behavior:
The app fails to load music. There are no errors or warnings provided to explain the issue.

Additional Information:

A screen recording demonstrating the issue has been attached.
The issue persists across multiple attempts.App is allowed through the firewall ✅

https://github.com/user-attachments/assets/499418d3-7c19-4ae5-81b2-f1b5cecab313

Version v2.10.9+154 (x64) works without any problems on the same system.

**Comment by pbanj** [comment]
Same on Android. 2.10.10 doesnt play songs, but 2.10.9 works just fine

**Comment by HemantKArya** [comment]
Thank you, guys for reporting the bug, fixed in latest update let me know if it is working now in your devices too.
https://github.com/HemantKArya/BloomeeTunes/releases/tag/v2.10.11%2B155

**Comment by pbanj** [comment]
Working on android. Thanks for the fast update

**Comment by Devsathome** [comment]
> Thank you, guys for reporting the bug, fixed in latest update let me know if it is working now in your devices too. https://github.com/HemantKArya/BloomeeTunes/releases/tag/v2.10.11%2B155

yes working fine thank u for spending your time on fixing ,

https://github.com/user-attachments/assets/3e247439-2887-4e08-855e-27d7b1181dc7
